
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import Navbar from '@/components/main/Navbar'
import Home from '@/components/main/Home'
import Footer from '@/components/main/Footer'
import { UserProvider } from '@auth0/nextjs-auth0/client';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='bg-black text-white'>
         <UserProvider>
            <Navbar />
            {children}
            <Footer />
         </UserProvider>
            
          
          
          
        </div>
        
      </body>
    </html>
  )
}
